In [1]:
import numpy as np
import pandas as pd

df = pd.read_excel('house_sample.xlsx')
df.head()

,标题,建筑面积,总价,户型,朝向,物 业 费,环比上月,张贴日期,产权性质,装修,楼层
0,资深经纪上海人：稀缺3房，南北通透采光好，房东急需用钱！,123.50,760,3室2厅0厨2卫,南北,1.5元/平米・月,↑1.44%,2017年4月12日,商品房,豪华装修,低层
1,未来规划小上海，精装带地暖，养老，亲子，旅游度假一体化,86.00,76,2室2厅1厨1卫,南北,1.8元/・月,↑4.08%,2017年4月13日,商品房,精装修,中层
2,双高铁 不限贷 买一层送一层 送大露台 看房专车接送,90.00,80,3室2厅1厨2卫,南北,暂无资料,↓0.01%,2017年4月14日,商品房,精装修,高层
3,坐拥嘉兴海宁双轨 享受市区配套 现房值得拥有 可落户,90.00,80,2室1厅1厨1卫,南北,暂无资料,↓0.01%,2017年4月15日,商品房,简装修,中层
4,对口明强校区，精装两房税费少，位置安静，媲美园艺新村，随时看,66.61,285,2室1厅1厨1卫,南,0.8元/平米・月,↓2.62%,2017年4月16日,个人产权,中装修,低层

### 针对字段的普通计算

In [2]:
#将总价转换为xx万的形式
df['总价'] * 10000

0     7600000
1      760000
2      800000
3      800000
4     2850000
5     2950000
6     2400000
7     4100000
8     4000000
9     2700000
10    3000000
11    2850000
12    3400000
13    3550000
14    8500000
15    3590000
16    3600000
17    6100000
18    7700000
19    2200000
20    2360000
21    2980000
22    3250000
23    4580000
25    5600000
26    6500000
27    2000000
28    2550000
29    4500000
Name: 总价, dtype: int64

In [3]:
np.sqrt(df['总价'])

0     27.568098
1      8.717798
2      8.944272
3      8.944272
4     16.881943
5     17.175564
6     15.491933
7     20.248457
8     20.000000
9     16.431677
10    17.320508
11    16.881943
12    18.439089
13    18.841444
14    29.154759
15    18.947295
16    18.973666
17    24.698178
18    27.748874
19    14.832397
20    15.362291
21    17.262677
22    18.027756
23    21.400935
25    23.664319
26    25.495098
27    14.142136
28    15.968719
29    21.213203
Name: 总价, dtype: float64

In [5]:
df['朝向'] + df['户型']  #合并操作必须保证字段类型要一致

0     南北3室2厅0厨2卫
1     南北2室2厅1厨1卫
2     南北3室2厅1厨2卫
3     南北2室1厅1厨1卫
4      南2室1厅1厨1卫
5     南北3室1厅1厨1卫
6      南2室1厅1厨1卫
7      南3室1厅1厨1卫
8      南2室2厅1厨1卫
9     南北1室1厅1厨1卫
10    南北2室1厅1厨1卫
11     南1室1厅1厨1卫
12    南北1室1厅1厨1卫
13    南北2室1厅1厨1卫
14    南北3室2厅1厨2卫
15     南2室1厅1厨1卫
16     南2室1厅1厨1卫
17    南北2室2厅1厨1卫
18     南3室2厅0厨2卫
19     南1室0厅1厨1卫
20    南北2室2厅1厨1卫
21     南1室2厅1厨1卫
22     南1室2厅1厨1卫
23    南北3室2厅1厨1卫
25    南北3室2厅1厨2卫
26     南2室2厅1厨2卫
27     南1室1厅1厨1卫
28    南北2室1厅1厨1卫
29     南2室1厅0厨1卫
dtype: object

In [6]:
df['均价'] = df['总价'] * 10000 / df['建筑面积']

In [8]:
df.head()

,标题,建筑面积,总价,户型,朝向,物 业 费,环比上月,张贴日期,产权性质,装修,楼层,均价
0,资深经纪上海人：稀缺3房，南北通透采光好，房东急需用钱！,123.50,760,3室2厅0厨2卫,南北,1.5元/平米・月,↑1.44%,2017年4月12日,商品房,豪华装修,低层,61538.461538
1,未来规划小上海，精装带地暖，养老，亲子，旅游度假一体化,86.00,76,2室2厅1厨1卫,南北,1.8元/・月,↑4.08%,2017年4月13日,商品房,精装修,中层,8837.209302
2,双高铁 不限贷 买一层送一层 送大露台 看房专车接送,90.00,80,3室2厅1厨2卫,南北,暂无资料,↓0.01%,2017年4月14日,商品房,精装修,高层,8888.888889
3,坐拥嘉兴海宁双轨 享受市区配套 现房值得拥有 可落户,90.00,80,2室1厅1厨1卫,南北,暂无资料,↓0.01%,2017年4月15日,商品房,简装修,中层,8888.888889
4,对口明强校区，精装两房税费少，位置安静，媲美园艺新村，随时看,66.61,285,2室1厅1厨1卫,南,0.8元/平米・月,↓2.62%,2017年4月16日,个人产权,中装修,低层,42786.368413

### 在字段上使用函数方法进行处理，Map, Apply, ApplyMap

In [9]:
#map方法的使用，map方法针对列中的每个元素进行处理
s = '1.5元/平米・月'
s.split('元')[0]

'1.5'

In [10]:
def removeDollar(e):
    return e.split('元')[0]

In [11]:
df['物 业 费'].map(removeDollar)

0      1.5
1      1.8
2     暂无资料
3     暂无资料
4      0.8
5      0.6
6      0.6
7      1.4
8     0.55
9     暂无资料
10     1.4
11    暂无资料
12     0.7
13     0.5
14    0.60
15     1.2
16     1.4
17     1.5
18     0.7
19     1.4
20     0.8
21    1.65
22    1.83
23    1.25
25    1.85
26    2.30
27     0.8
28    0.95
29     0.7
Name: 物 业 费, dtype: object

In [12]:
df['物 业 费'].map(lambda e: e.split('元')[0])

0      1.5
1      1.8
2     暂无资料
3     暂无资料
4      0.8
5      0.6
6      0.6
7      1.4
8     0.55
9     暂无资料
10     1.4
11    暂无资料
12     0.7
13     0.5
14    0.60
15     1.2
16     1.4
17     1.5
18     0.7
19     1.4
20     0.8
21    1.65
22    1.83
23    1.25
25    1.85
26    2.30
27     0.8
28    0.95
29     0.7
Name: 物 业 费, dtype: object

In [13]:
#apply方法可以针对整行或整列数据进行操作，axis=0为列， axis=1为行，有点类似于sql聚合函数。

df1 = pd.DataFrame([
    [60, 70, 50],
    [80, 79, 68],
    [63, 66, 82]
], columns=['first', 'second', 'third'])
df1

   first  second  third
0     60      70     50
1     80      79     68
2     63      66     82

In [15]:
df1.apply(lambda e: e.max() - e.min(), axis=1)

0    20
1    12
2    19
dtype: int64

In [16]:
#applymap是针对整个dataframe里面的每个元素进行操作
def convertNaN(e):
    if e == '暂无资料':
        return np.nan
    else:
        return e

df.applymap(convertNaN).head()

,标题,建筑面积,总价,户型,朝向,物 业 费,环比上月,张贴日期,产权性质,装修,楼层,均价
0,资深经纪上海人：稀缺3房，南北通透采光好，房东急需用钱！,123.50,760,3室2厅0厨2卫,南北,1.5元/平米・月,↑1.44%,2017年4月12日,商品房,豪华装修,低层,61538.461538
1,未来规划小上海，精装带地暖，养老，亲子，旅游度假一体化,86.00,76,2室2厅1厨1卫,南北,1.8元/・月,↑4.08%,2017年4月13日,商品房,精装修,中层,8837.209302
2,双高铁 不限贷 买一层送一层 送大露台 看房专车接送,90.00,80,3室2厅1厨2卫,南北,NaN,↓0.01%,2017年4月14日,商品房,精装修,高层,8888.888889
3,坐拥嘉兴海宁双轨 享受市区配套 现房值得拥有 可落户,90.00,80,2室1厅1厨1卫,南北,NaN,↓0.01%,2017年4月15日,商品房,简装修,中层,8888.888889
4,对口明强校区，精装两房税费少，位置安静，媲美园艺新村，随时看,66.61,285,2室1厅1厨1卫,南,0.8元/平米・月,↓2.62%,2017年4月16日,个人产权,中装修,低层,42786.368413

In [17]:
df.applymap(lambda e: np.nan if e=='暂无资料' else e).head()

,标题,建筑面积,总价,户型,朝向,物 业 费,环比上月,张贴日期,产权性质,装修,楼层,均价
0,资深经纪上海人：稀缺3房，南北通透采光好，房东急需用钱！,123.50,760,3室2厅0厨2卫,南北,1.5元/平米・月,↑1.44%,2017年4月12日,商品房,豪华装修,低层,61538.461538
1,未来规划小上海，精装带地暖，养老，亲子，旅游度假一体化,86.00,76,2室2厅1厨1卫,南北,1.8元/・月,↑4.08%,2017年4月13日,商品房,精装修,中层,8837.209302
2,双高铁 不限贷 买一层送一层 送大露台 看房专车接送,90.00,80,3室2厅1厨2卫,南北,NaN,↓0.01%,2017年4月14日,商品房,精装修,高层,8888.888889
3,坐拥嘉兴海宁双轨 享受市区配套 现房值得拥有 可落户,90.00,80,2室1厅1厨1卫,南北,NaN,↓0.01%,2017年4月15日,商品房,简装修,中层,8888.888889
4,对口明强校区，精装两房税费少，位置安静，媲美园艺新村，随时看,66.61,285,2室1厅1厨1卫,南,0.8元/平米・月,↓2.62%,2017年4月16日,个人产权,中装修,低层,42786.368413

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29 entries, 0 to 29
Data columns (total 12 columns):
标题       29 non-null object
建筑面积     29 non-null float64
总价       29 non-null int64
户型       29 non-null object
朝向       29 non-null object
物 业 费    29 non-null object
环比上月     29 non-null object
张贴日期     29 non-null object
产权性质     29 non-null object
装修       29 non-null object
楼层       29 non-null object
均价       29 non-null float64
dtypes: float64(2), int64(1), object(9)
memory usage: 2.9+ KB

## 时间日期格式的处理

In [21]:
from datetime import datetime, timedelta

s = '2018/12/31'
datetime.strptime(s, '%Y/%m/%d')

datetime.datetime(2018, 12, 31, 0, 0)

In [22]:
pd.to_datetime(df['张贴日期'], format='%Y年%m月%d日').head()

0   2017-04-12
1   2017-04-13
2   2017-04-14
3   2017-04-15
4   2017-04-16
Name: 张贴日期, dtype: datetime64[ns]

In [23]:
df['张贴日期'] = pd.to_datetime(df['张贴日期'], format='%Y年%m月%d日')

In [24]:
df.head()

,标题,建筑面积,总价,户型,朝向,物 业 费,环比上月,张贴日期,产权性质,装修,楼层,均价
0,资深经纪上海人：稀缺3房，南北通透采光好，房东急需用钱！,123.50,760,3室2厅0厨2卫,南北,1.5元/平米・月,↑1.44%,2017-04-12,商品房,豪华装修,低层,61538.461538
1,未来规划小上海，精装带地暖，养老，亲子，旅游度假一体化,86.00,76,2室2厅1厨1卫,南北,1.8元/・月,↑4.08%,2017-04-13,商品房,精装修,中层,8837.209302
2,双高铁 不限贷 买一层送一层 送大露台 看房专车接送,90.00,80,3室2厅1厨2卫,南北,暂无资料,↓0.01%,2017-04-14,商品房,精装修,高层,8888.888889
3,坐拥嘉兴海宁双轨 享受市区配套 现房值得拥有 可落户,90.00,80,2室1厅1厨1卫,南北,暂无资料,↓0.01%,2017-04-15,商品房,简装修,中层,8888.888889
4,对口明强校区，精装两房税费少，位置安静，媲美园艺新村，随时看,66.61,285,2室1厅1厨1卫,南,0.8元/平米・月,↓2.62%,2017-04-16,个人产权,中装修,低层,42786.368413

In [25]:
df['张贴日期'].head()

0   2017-04-12
1   2017-04-13
2   2017-04-14
3   2017-04-15
4   2017-04-16
Name: 张贴日期, dtype: datetime64[ns]

In [26]:
df['张贴日期'].iloc[0] - timedelta(days=1)

Timestamp('2017-04-11 00:00:00')

In [27]:
for i in range(1, 11):
    dt = df['张贴日期'].iloc[0] - timedelta(days=i)
    print(dt)

2017-04-11 00:00:00
2017-04-10 00:00:00
2017-04-09 00:00:00
2017-04-08 00:00:00
2017-04-07 00:00:00
2017-04-06 00:00:00
2017-04-05 00:00:00
2017-04-04 00:00:00
2017-04-03 00:00:00
2017-04-02 00:00:00

### 使用正则表达式抽取内容

In [29]:
df.head()

,标题,建筑面积,总价,户型,朝向,物 业 费,环比上月,张贴日期,产权性质,装修,楼层,均价
0,资深经纪上海人：稀缺3房，南北通透采光好，房东急需用钱！,123.50,760,3室2厅0厨2卫,南北,1.5元/平米・月,↑1.44%,2017-04-12,商品房,豪华装修,低层,61538.461538
1,未来规划小上海，精装带地暖，养老，亲子，旅游度假一体化,86.00,76,2室2厅1厨1卫,南北,1.8元/・月,↑4.08%,2017-04-13,商品房,精装修,中层,8837.209302
2,双高铁 不限贷 买一层送一层 送大露台 看房专车接送,90.00,80,3室2厅1厨2卫,南北,暂无资料,↓0.01%,2017-04-14,商品房,精装修,高层,8888.888889
3,坐拥嘉兴海宁双轨 享受市区配套 现房值得拥有 可落户,90.00,80,2室1厅1厨1卫,南北,暂无资料,↓0.01%,2017-04-15,商品房,简装修,中层,8888.888889
4,对口明强校区，精装两房税费少，位置安静，媲美园艺新村，随时看,66.61,285,2室1厅1厨1卫,南,0.8元/平米・月,↓2.62%,2017-04-16,个人产权,中装修,低层,42786.368413

In [30]:
df['户型'].str.extract('(\d+)室(\d+)厅(\d+)厨(\d+)卫').head()

   0  1  2  3
0  3  2  0  2
1  2  2  1  1
2  3  2  1  2
3  2  1  1  1
4  2  1  1  1

In [31]:
df[['室', '厅', '厨', '卫']] = df['户型'].str.extract('(\d+)室(\d+)厅(\d+)厨(\d+)卫')
df.head()

,标题,建筑面积,总价,户型,朝向,物 业 费,环比上月,张贴日期,产权性质,装修,楼层,均价,室,厅,厨,卫
0,资深经纪上海人：稀缺3房，南北通透采光好，房东急需用钱！,123.50,760,3室2厅0厨2卫,南北,1.5元/平米・月,↑1.44%,2017-04-12,商品房,豪华装修,低层,61538.461538,3,2,0,2
1,未来规划小上海，精装带地暖，养老，亲子，旅游度假一体化,86.00,76,2室2厅1厨1卫,南北,1.8元/・月,↑4.08%,2017-04-13,商品房,精装修,中层,8837.209302,2,2,1,1
2,双高铁 不限贷 买一层送一层 送大露台 看房专车接送,90.00,80,3室2厅1厨2卫,南北,暂无资料,↓0.01%,2017-04-14,商品房,精装修,高层,8888.888889,3,2,1,2
3,坐拥嘉兴海宁双轨 享受市区配套 现房值得拥有 可落户,90.00,80,2室1厅1厨1卫,南北,暂无资料,↓0.01%,2017-04-15,商品房,简装修,中层,8888.888889,2,1,1,1
4,对口明强校区，精装两房税费少，位置安静，媲美园艺新村，随时看,66.61,285,2室1厅1厨1卫,南,0.8元/平米・月,↓2.62%,2017-04-16,个人产权,中装修,低层,42786.368413,2,1,1,1

In [32]:
del df['户型']
df.head()

,标题,建筑面积,总价,朝向,物 业 费,环比上月,张贴日期,产权性质,装修,楼层,均价,室,厅,厨,卫
0,资深经纪上海人：稀缺3房，南北通透采光好，房东急需用钱！,123.50,760,南北,1.5元/平米・月,↑1.44%,2017-04-12,商品房,豪华装修,低层,61538.461538,3,2,0,2
1,未来规划小上海，精装带地暖，养老，亲子，旅游度假一体化,86.00,76,南北,1.8元/・月,↑4.08%,2017-04-13,商品房,精装修,中层,8837.209302,2,2,1,1
2,双高铁 不限贷 买一层送一层 送大露台 看房专车接送,90.00,80,南北,暂无资料,↓0.01%,2017-04-14,商品房,精装修,高层,8888.888889,3,2,1,2
3,坐拥嘉兴海宁双轨 享受市区配套 现房值得拥有 可落户,90.00,80,南北,暂无资料,↓0.01%,2017-04-15,商品房,简装修,中层,8888.888889,2,1,1,1
4,对口明强校区，精装两房税费少，位置安静，媲美园艺新村，随时看,66.61,285,南,0.8元/平米・月,↓2.62%,2017-04-16,个人产权,中装修,低层,42786.368413,2,1,1,1